CREATE DATABASE IF NOT EXISTS eventdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE eventdb;

-- Roles seed
CREATE TABLE IF NOT EXISTS roles (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

INSERT IGNORE INTO roles (name) VALUES ('ROLE_ADMIN'), ('ROLE_ORGANIZER'), ('ROLE_ATTENDEE');
